---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
