apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../bases/
  - ../../vendor/katalog/monitoring/eks-sm
  - resources/ingress.yml

patchesStrategicMerge:
  - patches/ingress-nginx-lb-annotation.yml
